### ISSUE TITLE
Incremental Update Of Images/Content

### ISSUE THREAD

**Issue by MorganRodgers** [MorganRodgers/Macroinvertebrate-Field-Guide#11]
Currently content loads from disk first; if a sync is requested that same content will show until everything is ready. Once it is ready the streams and invertebrates are locked, the internal stores are updated, unlocked, and then written to disk.

It might be preferable to instead do an incremental update which is the behavior in the iOS application.

**Comment by MorganRodgers** [comment]
Decision needed before 1.0. This isn't a functional problem, just a UX choice. @pclemins: thoughts?

**Comment by MorganRodgers** [comment]
Incremental is a much nicer UX. As a side bennie we save a bit of memory by not having parallel data structures going at the same time. In case of failure/interruption we DO NOT overwrite the local storage.

**Comment by pclemins** [comment]
I'd vote for incremental so that as it updates, you can see it happen....

Pat
