### ISSUE TITLE
Pop notification that sync is running

### ISSUE THREAD

**Issue by MorganRodgers** [MorganRodgers/Macroinvertebrate-Field-Guide#13]
Currently there is not a notification to the user that the update process is running. I'd like to throw up less modal popups than the iOS version, but some are still indicated.

**Comment by pclemins** [comment]
Yes!  Love this idea... I thought of this too.  Maybe a little line at the
bottom of the screen that slides up?

**Comment by MorganRodgers** [comment]
The windows are all instances of QMainWindow which includes a message bar at the bottom. It's a fairly low-key way to letting users know that the application is doing something. Something I've noticed users don't often realize is even there. We could use that to provide incremental status updates.

**Comment by MorganRodgers** [comment]
The first run allows the user to decide whether to start sync, and clicking the sync button also pops a modal which confirms the job has started and provides the option to stop it. Done.
