### ISSUE TITLE
Message That The Field Guide is Incomplete/How to Contribute

### ISSUE THREAD

**Issue by MorganRodgers** [MorganRodgers/Macroinvertebrate-Field-Guide#22]
Given that some streams have so few entries it might be worthwhile to have a message that conditionally shows on such pages requesting help identifying/adding content to the Wiki.

@pclemins thoughts?

**Comment by pclemins** [comment]
This is a good idea, but just a few entries in a stream isn't a good
indicator that the wiki needs editing... some streams have very little
diversity.  Maybe this could be the default message in the status indicator
when there isn't a need to display any sync messages...  OR, we figure out
some other indicator for the message....
