### ISSUE TITLE
Make Date Last Synced a more readable format

### ISSUE THREAD

**Issue by pclemins** [MorganRodgers/Macroinvertebrate-Field-Guide#31]
Right now, it's in a raw, very computer-readable format.  It should be something like:

7/6/2016 at 13:34

**Comment by MorganRodgers** [comment]
I've changed from the default to Qt::SystemLocaleShortDate which in my locale gives the format of "7/7/16 10:12 AM". That enum claims to respect the system's settings, so it should be user customizable.
