### ISSUE TITLE
Instant Search?

### ISSUE THREAD

**Issue by pclemins** [MorganRodgers/Macroinvertebrate-Field-Guide#37]
Can we make the search box on the Stream list screen update the streams as you type?

**Comment by MorganRodgers** [comment]
Search is already bound to the textChanged signal. It looks like that signal doesn't fire until after

**Comment by MorganRodgers** [comment]
The events keyPressEvent, keyReleaseEvent on the main widget, or the textEdited signal on the LineEdit itself only fire after the device's softkeyboard returns. So I don't think that there is a way to do this from C++. There might be a way to do it from Android's native Java, but I'd put that off until a later version.

**Comment by MorganRodgers** [comment]
This seems to be keyboard dependent. The Hacker's Keyboard in landscape orientation gives a live update on each key stroke. If we provided our own keyboard implementation we might be able to get live updates.
