### ISSUE TITLE
Sync/Parsing is Generating Weird Results

### ISSUE THREAD

**Issue by MorganRodgers** [MorganRodgers/Macroinvertebrate-Field-Guide#6]
There're some invertebrates that are getting no family/genus/order set. Others have their image set but imageIsUpToDate isn't set.

**Comment by MorganRodgers** [comment]
It looks the like the data is bad in general. Some invertebrates have multiple STOP statements in their text sections, there's quite a bit of missing data.

**Comment by pclemins** [comment]
Family / Genus / Order being empty is fine as long as one is set... 

But, the multiple STOP statements, we should fix.  If we can quickly write to log those templates with multiple stop statements, we can send that to Declan to fix...

**Comment by MorganRodgers** [comment]
I wrote a validator this morning and wasn't able to find examples of multiple STOP statements. Between that and it being acceptable to have one or more of Family, Genus, Order empty this is a non-issue.
