### ISSUE TITLE
Use Authenticated API

### ISSUE THREAD

**Issue by MorganRodgers** [MorganRodgers/Macroinvertebrate-Field-Guide#7]
Bots are allowed 500 query results per call opposed to the 50 we're currently limited to.

**Comment by MorganRodgers** [comment]
Human account requested from WikiEducator.

**Comment by MorganRodgers** [comment]
Note/Reminder that we'll end up having credentials in the application, and that I should NOT commit those credentials to the public repository.

**Comment by pclemins** [comment]
I suppose we should make it an option to have people enter their own
credentials so they can use "bot mode", right?

**Comment by MorganRodgers** [comment]
We could do that, but I think we'd find that most people wouldn't use it because they wouldn't create accounts with bot access.

Or we could put a place holder file into the repo with a bogus username/password combo and communicate the real combination securely to the person compiling/deploying the application. Here be the dangers of public repos...

**Comment by pclemins** [comment]
Oh yeah... that would work as well :)

**Comment by MorganRodgers** [comment]
I wonder if deploying something like this to the masses would be a violation of ToS? Something to look into.

**Comment by pclemins** [comment]
I'm not sure this is any worse than what we are doing now... unless you
share a common login for the bot across all installs of the field guide.
Right now, we actually use more resources as 10 separate 50 bug requests is
much more load on the server than a single 500 bug request....

**Comment by MorganRodgers** [comment]
What I'm wondering about is
